adam_epsilon: 1.0e-08
data_dir: data
early_stop_callback: false
eval_batch_size: 4
fp_16: false
gradient_accumulation_steps: 1
learning_rate: 0.0003
max_grad_norm: 1.0
max_input_length: 16
max_target_length: 4
model_name_or_path: sonoisa/t5-base-japanese
n_gpu: 1
num_train_epochs: 8
opt_level: O1
seed: 42
tokenizer_name_or_path: sonoisa/t5-base-japanese
train_batch_size: 4
warmup_steps: 0
weight_decay: 0.0
